import {
  GEMINI_API_KEY,
  GIPHY_API_KEY,
  EDEN_API_KEY,
  POLINATION_AI_API_KEY,
  PICSART_API_KEY,
} from '@env';

export const ENV = {
  GEMINI_API_KEY: GEMINI_API_KEY || '',
  GIPHY_API_KEY: GIPHY_API_KEY || '',
  EDEN_API_KEY: EDEN_API_KEY || '',
  POLINATION_AI_API_KEY: POLINATION_AI_API_KEY || '',
  PICSART_API_KEY: PICSART_API_KEY || '',
};
