export interface ThemeProperties {
  baseColor: string;
  washColors: string[];
  spotlightColor: string;
  accentColor: string;
  textColor: string;
  secondaryTextColor: string;
  borderColor: string;
  isDark: boolean;
  themeName: string;
}

export const THEMES: Record<string, ThemeProperties> = {
  "Cosmic Slate": {
    baseColor: "#0E1214",
    washColors: ["rgba(30, 41, 59, 0.3)", "rgba(15, 23, 42, 0.2)", "rgba(16, 185, 129, 0.1)"],
    spotlightColor: "#10B981",
    accentColor: "#10B981",
    textColor: "#FFFFFF",
    secondaryTextColor: "#94A3B8",
    borderColor: "rgba(255, 255, 255, 0.08)",
    isDark: true,
    themeName: "Cosmic Slate"
  },
  "Cyber Neon": {
    baseColor: "#000000",
    washColors: ["rgba(30, 16, 47, 0.35)", "rgba(10, 21, 32, 0.25)", "#000000"],
    spotlightColor: "#00FFCC",
    accentColor: "#00FFCC",
    textColor: "#FFFFFF",
    secondaryTextColor: "#8A8A8F",
    borderColor: "rgba(0, 255, 204, 0.15)",
    isDark: true,
    themeName: "Cyber Neon"
  },
  "Rose Gold": {
    baseColor: "#120E11",
    washColors: ["rgba(46, 27, 36, 0.3)", "rgba(34, 21, 27, 0.2)", "rgba(253, 164, 175, 0.1)"],
    spotlightColor: "#FDA4AF",
    accentColor: "#FDA4AF",
    textColor: "#FFFFFF",
    secondaryTextColor: "#FDA4AF",
    borderColor: "rgba(253, 164, 175, 0.1)",
    isDark: true,
    themeName: "Rose Gold"
  },
  "Solar Eclipse": {
    baseColor: "#140F08",
    washColors: ["rgba(42, 25, 5, 0.35)", "rgba(30, 17, 2, 0.25)", "rgba(251, 191, 36, 0.1)"],
    spotlightColor: "#FBBF24",
    accentColor: "#FBBF24",
    textColor: "#FFFFFF",
    secondaryTextColor: "#FBBF24",
    borderColor: "rgba(251, 191, 36, 0.12)",
    isDark: true,
    themeName: "Solar Eclipse"
  },
  "Pure Light": {
    baseColor: "#F8FAFC",
    washColors: ["rgba(226, 232, 240, 0.6)", "rgba(203, 213, 225, 0.5)", "rgba(59, 130, 246, 0.08)"],
    spotlightColor: "#3B82F6",
    accentColor: "#3B82F6",
    textColor: "#0F172A",
    secondaryTextColor: "#475569",
    borderColor: "rgba(15, 23, 42, 0.08)",
    isDark: false,
    themeName: "Pure Light"
  },
  "Dark Void": {
    baseColor: "#0A0A0A",
    washColors: ["rgba(72, 103, 175, 0.25)", "rgba(156, 175, 184, 0.15)", "rgba(196, 149, 119, 0.15)"],
    spotlightColor: "#6B62F2",
    accentColor: "#6B62F2",
    textColor: "#FFFFFF",
    secondaryTextColor: "#8E8E93",
    borderColor: "rgba(255, 255, 255, 0.08)",
    isDark: true,
    themeName: "Dark Void"
  }
};

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  FR: {
    settings_title: "Configuration Globale",
    settings_subtitle: "Personnalise ton expérience MemeGen AI",
    welcome_desc: "Crée des Mèmes, Stickers, GIFs de situation & courtes Vidéos Animées instantanément avec l'intelligence de Gemini 3.5 !",
    btn_start_experience: "DÉBUTER L'EXPÉRIENCE",
    welcome_prep: "Préparation de ton studio créatif...",
    welcome_title: "BIENVENUE",
    vibe_ready: "Prêt à transformer ton humeur.",
    context_active: "Le mode Lecteur de Contexte est actif",
    tab_emoji_label: "Emoji",
    tab_sticker_label: "Sticker",
    tab_gif_label: "GIF",
    lang_label: "Langue de l'application",
    edition_label: "Mode d'Édition Actif",
    theme_label: "Thème Visuel",
    others_label: "Autres Préférences",
    safe_search: "Filtre Contenu Gemini (IA)",
    sound_fx: "Sons & Retours Tactiles",
    autoplay: "Lecture Auto (TikTok GIFs)",
    active_badge: "Licence Active",
    desc_title: "Mème Studio",
    save_success: "Enregistré avec succès !",
    save_err: "Erreur lors de la sauvegarde",
    tab_text: "Texte",
    tab_audio: "Vocal",
    tab_photo: "Photo",
    tab_archive: "Archive",
    tab_settings: "Réglages",
    current_badge: "Édition active",
    context_title: "Lecteur de Contexte (Texte)",
    context_desc: "Saisis une discussion, une situation de vie, ou une frustration quotidienne. L'IA Gemini va analyser le contexte pour en faire un mème parfait !",
    context_label: "Situation ou discussion",
    context_placeholder: "Ex: Quand le prof dit qu'il n'y a pas de rattrapage mais que tout le monde a eu 5/20...",
    prompt_format: "Format de génération du mème :",
    btn_generate_text: "GÉNÉRER MÈME TEXTE IA",
    bg_title: "🎨 Fond d'image personnalisé",
    bg_bonus: "Prompt IA pour générer le fond (Optionnel)",
    bg_placeholder: "Ex: un chat stressé devant un ordinateur, style cartoon 3D",
    live_preview: "Aperçu en Direct",
    btn_save: "SAUVEGARDER",
    btn_share: "PARTAGER",
    voice_to_meme_title: "🎙️ Voice-To-Meme",
    voice_to_meme_desc: "Enregistre une note vocale. L'IA va la transcrire, analyser l'émotion ou le ton, et générer un mème textuel avec la transcription en sous-titre.",
    recording_in_progress: "🔴 Enregistrement en cours (Appuie pour arrêter)",
    tap_to_record: "Toucher pour enregistrer de l'audio",
    simulate_voice_note: "📢 Simuler une note vocale (Pratique pour émulateur) :",
    voice_note_transcription: "Transcription de la Note Vocale",
    preview: "Aperçu :",
    photo_remixer_title: "📸 Status Remixer (Uploader Photo)",
    photo_remixer_desc: "Télécharge une image de ton téléphone. Notre IA analysera instantanément ton image afin de suggérer des punchlines drôles à superposer dessus.",
    btn_gallery: "GALERIE",
    btn_edit: "ÉDITER",
    legend_top: "Légende supérieure (Haut)",
    legend_bottom: "Légende inférieure (Bas)",
    image_analyzing: "Analyse de l'image par Gemini IA...",
    no_memes_saved: "Aucun mème sauvegardé !",
    library_empty_tip: "Laisse libre cours à ton génie comique sous l'un des trois autres onglets !",
    filter_all: "📁 Tout",
    filter_memes: "🧠 Mèmes",
    filter_stickers: "🎨 Stickers",
    filter_gifs: "🎬 GIFs",
    filter_videos: "📺 Vidéos",
    created_memes: "📁 Tes Mèmes Créés :",
    archive_filter_empty: "Aucun élément de ce type dans ton archive !",
    menu_actions_title: "Menu Actions Mème",
    what_to_do_question: "Qu'aimerais-tu faire de ton chef-d'œuvre ?",
    btn_share_label: "Partager",
    btn_delete_label: "Supprimer",
    btn_close_label: "FERMER",
    meme_deleted: "Mème effacé de l'archive.",
    desc_pro: "Génération illimitée, formats HD",
    desc_enterprise: "Partages collaboratifs & exports",
    desc_developer: "Console debug & logs IA Gemini",
    desc_standard: "Outils standards et mèmes",
    desc_safe_search: "Filtre proactif des contenus offensants",
    desc_sound_fx: "Retour haptic et alertes audio",
    studio_title: "Studio d'Expression IA",
    studio_desc: "En plus du mème classique, convertis ta situation en stickers personnalisés, GIF de réaction ou courte vidéo TikTok animée !",
    studio_sticker: "Sticker IA",
    studio_gif: "GIF Situation",
    studio_video: "Short Vidéo",
    generating_sticker: "Génération du sticker par l'IA...",
    generating_gif: "Recherche de situation par l'IA...",
    generating_video: "Production du storyboard animé...",
    btn_generate_sticker: "GÉNÉRER STICKER IA",
    btn_generate_gif: "GÉNÉRER GIF SITUATION IA",
    btn_generate_video: "GÉNÉRER SHORT VIDÉO IA",
    customize_sticker: "🎨 Personnalise ton Sticker IA :",
    sticker_slogan_label: "Modifier le slogan du Sticker",
    sticker_tip: "Astuce: Appuie sur le sticker pour le secouer !",
    sticker_saved: "Sticker sauvegardé !",
    gif_saved: "GIF de situation enregistré !",
    video_saved: "Short Vidéo Animée enregistrée !",
    btn_save_sticker: "SAUVEGARDER LE STICKER",
    btn_save_gif: "SAUVEGARDER LE GIF DE SITUATION",
    btn_save_video: "SAUVEGARDER LA SHORT VIDÉO ANIMÉE",
    gif_title: "🎬 GIF de Situation IA :",
    video_title: "📺 Short Vidéo Animée IA :"
  },
  EN: {
    settings_title: "Global Settings",
    settings_subtitle: "Customize your MemeGen AI experience",
    welcome_desc: "Create Memes, Stickers, situation GIFs & short animated Videos instantly with the power of Gemini 3.5!",
    btn_start_experience: "START THE EXPERIENCE",
    welcome_prep: "Preparing your creative studio...",
    welcome_title: "WELCOME",
    vibe_ready: "Ready to transform your vibe.",
    context_active: "Context Reader mode is active",
    tab_emoji_label: "Emoji",
    tab_sticker_label: "Sticker",
    tab_gif_label: "GIF",
    lang_label: "App Language",
    edition_label: "Active App Edition",
    theme_label: "Visual Theme",
    others_label: "Other Preferences",
    safe_search: "Gemini Content Safe Search (AI)",
    sound_fx: "Sound FX & Haptic Feedback",
    autoplay: "Autoplay (TikTok GIFs)",
    active_badge: "Active License",
    desc_title: "Meme Studio",
    save_success: "Saved successfully!",
    save_err: "Error during save",
    tab_text: "Text",
    tab_audio: "Voice",
    tab_photo: "Photo",
    tab_archive: "Archive",
    tab_settings: "Settings",
    current_badge: "Active Edition",
    context_title: "Context Reader (Text)",
    context_desc: "Enter a discussion, a life situation, or a daily frustration. Gemini AI will analyze the context to make a perfect meme!",
    context_label: "Situation or discussion",
    context_placeholder: "e.g., When the teacher says there is no makeup exam but everyone got 5/20...",
    prompt_format: "Meme generation format:",
    btn_generate_text: "GENERATE AI TEXT MEME",
    bg_title: "🎨 Custom image background",
    bg_bonus: "AI Prompt to generate background (Optional)",
    bg_placeholder: "e.g., a stressed cat in front of a computer, 3D cartoon style",
    live_preview: "Live Preview",
    btn_save: "SAVE",
    btn_share: "SHARE",
    voice_to_meme_title: "🎙️ Voice-To-Meme",
    voice_to_meme_desc: "Record a voice note. The AI will transcribe it, analyze the emotion or tone, and generate a text meme with the transcription as subtitles.",
    recording_in_progress: "🔴 Recording in progress (Tap to stop)",
    tap_to_record: "Tap to record audio",
    simulate_voice_note: "📢 Simulate a voice note (Convenient for emulator):",
    voice_note_transcription: "Voice Note Transcription",
    preview: "Preview:",
    photo_remixer_title: "📸 Status Remixer (Photo Upload)",
    photo_remixer_desc: "Upload an image from your phone. Our AI will instantly analyze your image to suggest funny punchlines to overlay on it.",
    btn_gallery: "GALLERY",
    btn_edit: "EDIT",
    legend_top: "Upper Legend (Top)",
    legend_bottom: "Lower Legend (Bottom)",
    image_analyzing: "Analyzing image with Gemini AI...",
    no_memes_saved: "No saved memes!",
    library_empty_tip: "Let your comic genius run wild under one of the other three tabs!",
    filter_all: "📁 All",
    filter_memes: "🧠 Memes",
    filter_stickers: "🎨 Stickers",
    filter_gifs: "🎬 GIFs",
    filter_videos: "📺 Videos",
    created_memes: "📁 Your Created Memes:",
    archive_filter_empty: "No elements of this type in your archive!",
    menu_actions_title: "Meme Actions Menu",
    what_to_do_question: "What would you like to do with your masterpiece?",
    btn_share_label: "Share",
    btn_delete_label: "Delete",
    btn_close_label: "CLOSE",
    meme_deleted: "Meme deleted from archive.",
    desc_pro: "Unlimited generation, HD formats",
    desc_enterprise: "Collaborative sharing & exports",
    desc_developer: "Debug console & Gemini AI logs",
    desc_standard: "Standard tools and memes",
    desc_safe_search: "Proactive filtering of offensive content",
    desc_sound_fx: "Haptic feedback and audio alerts",
    studio_title: "AI Expression Studio",
    studio_desc: "In addition to the classic meme, convert your situation into custom stickers, reaction GIFs, or a short animated TikTok video!",
    studio_sticker: "AI Sticker",
    studio_gif: "Situation GIF",
    studio_video: "Short Video",
    generating_sticker: "Generating sticker by AI...",
    generating_gif: "Searching situation by AI...",
    generating_video: "Producing animated storyboard...",
    btn_generate_sticker: "GENERATE AI STICKER",
    btn_generate_gif: "GENERATE SITUATION GIF",
    btn_generate_video: "GENERATE SHORT VIDEO",
    customize_sticker: "🎨 Customize your AI Sticker:",
    sticker_slogan_label: "Edit Sticker slogan",
    sticker_tip: "Tip: Tap the sticker to shake it!",
    sticker_saved: "Sticker saved!",
    gif_saved: "Situation GIF saved!",
    video_saved: "Animated Short Video saved!",
    btn_save_sticker: "SAVE STICKER",
    btn_save_gif: "SAVE SITUATION GIF",
    btn_save_video: "SAVE ANIMATED SHORT VIDEO",
    gif_title: "🎬 AI Situation GIF:",
    video_title: "📺 AI Animated Short Video:"
  }
};
